using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using QuestPDF.Helpers;
using MAMS.Models.ViewModels.Reports;

namespace MAMS.Services.Reports
{
    public class DoctorAppointmentSummaryPdfDocument : IDocument
    {
        private readonly List<DoctorAppointmentSummaryViewModel> _appointments;
        private readonly DateTime _reportDate;

        public DoctorAppointmentSummaryPdfDocument(List<DoctorAppointmentSummaryViewModel> appointments, DateTime reportDate)
        {
            _appointments = appointments;
            _reportDate = reportDate;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(x => x.FontSize(10));
                page.PageColor(Colors.White);

                page.Header()
                    .Row(row =>
                    {
                        row.ConstantItem(60).Image("wwwroot/img/MedEase.png");

                        row.RelativeItem().AlignRight().Column(col =>
                        {
                            col.Item().Text("MAMS - Doctor Appointment Summary")
                                .FontSize(16).Bold().FontColor(Colors.Blue.Medium);
                            col.Item().Text($"Date: {_reportDate:dd/MM/yyyy}")
                                .FontSize(10).FontColor(Colors.Grey.Darken2);
                        });
                    });

                page.Content()
                    .PaddingVertical(15)
                    .Column(col =>
                    {
                        col.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                        col.Spacing(5);
                        
                        // Table headers
                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.ConstantColumn(40); // #
                                columns.RelativeColumn(); // Patient
                                columns.RelativeColumn(); // Doctor
                                columns.RelativeColumn(); // Specialization
                                columns.ConstantColumn(70); // Day
                                columns.ConstantColumn(80); // Time
                                columns.ConstantColumn(60); // Status
                            });

                            // Header row
                            table.Header(header =>
                            {
                                header.Cell().Element(CellStyle).Text("#").Bold();
                                header.Cell().Element(CellStyle).Text("Patient").Bold();
                                header.Cell().Element(CellStyle).Text("Doctor").Bold();
                                header.Cell().Element(CellStyle).Text("Specialization").Bold();
                                header.Cell().Element(CellStyle).Text("Day").Bold();
                                header.Cell().Element(CellStyle).Text("Time").Bold();
                                header.Cell().Element(CellStyle).Text("Status").Bold();

                                static IContainer CellStyle(IContainer container) =>
                                    container.Padding(5).Background(Colors.Grey.Lighten2).BorderBottom(1).AlignCenter();
                            });

                            // Data rows
                            foreach (var item in _appointments)
                            {
                                table.Cell().Element(CellData).Text(item.AppointmentNumber.ToString());
                                table.Cell().Element(CellData).Text(item.PatientName);
                                table.Cell().Element(CellData).Text(item.DoctorName);
                                table.Cell().Element(CellData).Text(item.Specialization);
                                table.Cell().Element(CellData).Text(item.Available_Day);
                                table.Cell().Element(CellData).Text(item.TimeSlot);
                                table.Cell().Element(CellData).Text(item.Status == 1 ? "Active" : "Inactive");

                                static IContainer CellData(IContainer container) =>
                                    container.Padding(5).BorderBottom(1).AlignCenter();
                            }
                        });
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(txt =>
                    {
                        txt.Span("Generated by ").FontSize(9);
                        txt.Span("MAMS").Bold().FontColor(Colors.Blue.Medium).FontSize(9);
                        txt.Span(" | ").FontSize(9);
                        txt.Span($"{DateTime.Now:dd/MM/yyyy HH:mm}").FontSize(9).FontColor(Colors.Grey.Medium);
                    });
            });
        }
    }
}
