using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using MAMS.Models.ViewModels.Reports;

namespace MAMS.Services.Reports
{
    public class LabSummaryReportPdfDocument : IDocument
    {
        private readonly List<LabBookingSummaryViewModel> _report;
        private readonly DateTime _date;

        public LabSummaryReportPdfDocument(List<LabBookingSummaryViewModel> report, DateTime date)
        {
            _report = report;
            _date = date;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);

                page.Header()
                    .Row(row =>
                    {
                        row.ConstantItem(60).Image("wwwroot/img/MedEase.png");

                        row.RelativeItem().Column(col =>
                        {
                            col.Item().AlignCenter().Text("MedEase™ - Daily Lab Summary Report").FontSize(16).Bold();
                            col.Item().AlignCenter().Text($"Date: {_date:dd/MM/yyyy}").FontSize(10);
                        });
                    });

                page.Content()
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(CellStyle).Text("Ref No").FontSize(9).Bold();
                            header.Cell().Element(CellStyle).Text("Patient").FontSize(9).Bold();
                            header.Cell().Element(CellStyle).Text("Lab Test").FontSize(9).Bold();
                            header.Cell().Element(CellStyle).Text("Booked Date").FontSize(9).Bold();
                            header.Cell().Element(CellStyle).Text("Time Slot").FontSize(9).Bold();
                            header.Cell().Element(CellStyle).Text("Payment Method").FontSize(9).Bold();
                            header.Cell().Element(CellStyle).Text("Amount").FontSize(9).Bold();
                            header.Cell().Element(CellStyle).Text("Issued Date").FontSize(9).Bold();
                        });

                        foreach (var item in _report)
                        {
                            table.Cell().Element(CellStyle).Text(item.ReferenceNo).FontSize(9);
                            table.Cell().Element(CellStyle).Text(item.PatientName).FontSize(9);
                            table.Cell().Element(CellStyle).Text(item.LabName).FontSize(9);
                            table.Cell().Element(CellStyle).Text(item.BookedDate.ToString("dd/MM/yyyy")).FontSize(9);
                            table.Cell().Element(CellStyle).Text(item.TimeSlot).FontSize(9);
                            table.Cell().Element(CellStyle).Text(item.PaymentMethod).FontSize(9);
                            table.Cell().Element(CellStyle).Text($"Rs. {item.TotalPaid:F2}").FontSize(9);
                            table.Cell().Element(CellStyle).Text(item.IssuedDate?.ToString("dd/MM/yyyy HH:mm")).FontSize(9);
                        }
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(txt =>
                    {
                        txt.Span("Generated by ").FontSize(9);
                        txt.Span("MAMS").Bold().FontColor(Colors.Blue.Medium).FontSize(9);
                        txt.Span(" | ").FontSize(9);
                        txt.Span($"{DateTime.Now:dd/MM/yyyy HH:mm}").FontSize(9).FontColor(Colors.Grey.Medium);
                    });
            });
        }

        private IContainer CellStyle(IContainer container)
        {
            return container.PaddingVertical(4).PaddingHorizontal(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
        }
    }
}
