using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using MAMS.Models.ViewModels.Reports;

namespace MAMS.Reports.Documents
{
    public class RevenueSummaryPdfDocument : IDocument
    {
        private readonly RevenueSummaryViewModel _model;
        private readonly DateTime _reportDate;

        public RevenueSummaryPdfDocument(RevenueSummaryViewModel model, DateTime reportDate)
        {
            _model = model;
            _reportDate = reportDate;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.Size(PageSizes.A4);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(12));
                // Watermark logo in background
                page.Background().ZIndex(0).AlignCenter().Image("wwwroot/img/MedEase.png", ImageScaling.FitHeight);

                page.Header().Element(ComposeHeader);
                page.Content().Element(ComposeContent);
                page.Footer().AlignCenter()
                .Text(txt =>
                {
                    txt.Span("Generated by ").FontSize(9);
                    txt.Span("MAMS").Bold().FontColor(Colors.Blue.Medium).FontSize(9);
                    txt.Span(" | ").FontSize(9);
                    txt.Span($"{DateTime.Now:dd/MM/yyyy HH:mm}").FontSize(9).FontColor(Colors.Grey.Medium);
                });
            });
        }

        private void ComposeHeader(IContainer container)
        {
            container.Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("MedEase™").Bold().FontSize(16).FontColor(Colors.Blue.Darken2);
                    col.Item().Text("Revenue Summary Report").FontSize(14);
                    col.Item().Text($"Date: {_reportDate:dd/MM/yyyy}").FontSize(11);
                    col.Item().PaddingVertical(5).LineHorizontal(1); // Horizontal line
                });

                row.ConstantItem(60).AlignRight().Image("wwwroot/img/MedEase.png");
            });
        }

        private void ComposeContent(IContainer container)
        {
            container.PaddingTop(10).Column(col =>
            {
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(1);
                        columns.RelativeColumn(1);
                    });

                    table.Header(header =>
                    {
                        header.Cell().Element(CellStyle).Text("Category").Bold();
                        header.Cell().Element(CellStyle).Text("Value").Bold();
                    });

                    void AddRow(string label, string value)
                    {
                        table.Cell().Element(CellStyle).Text(label);
                        table.Cell().Element(CellStyle).Text(value);
                    }

                    AddRow("Doctor Appointments", _model.DoctorAppointments.ToString());
                    AddRow("Doctor Revenue", $"Rs. {_model.DoctorRevenue:N2}");
                    AddRow("Lab Bookings", _model.LabBookings.ToString());
                    AddRow("Lab Revenue", $"Rs. {_model.LabRevenue:N2}");
                    AddRow("Total Transactions", _model.TotalTransactions.ToString());
                    AddRow("Total Revenue", $"Rs. {_model.TotalRevenue:N2}");

                    table.Cell().ColumnSpan(2).PaddingVertical(5).Element(CellStyle).LineHorizontal(0.5f);

                    AddRow("Cash Revenue", $"Rs. {_model.CashRevenue:N2}");
                    AddRow("Card Revenue", $"Rs. {_model.CardRevenue:N2}");
                    AddRow("Online Revenue", $"Rs. {_model.OnlineRevenue:N2}");
                });
            });
        }

        private static IContainer CellStyle(IContainer container)
        {
            return container.PaddingVertical(4).PaddingHorizontal(8);
        }
    }
}
