// <auto-generated />
using System;
using MAMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAMS.API.Migrations
{
    [DbContext(typeof(ApiDataContext))]
    [Migration("20250525174902_newDoctorDetails")]
    partial class newDoctorDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MAMS.API.Models.Appointments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Appoinment_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Appointment_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Availability_Id")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorAvailableDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("Doctor_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("User_PersonalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorAvailableDetailsId");

                    b.HasIndex("DoctorDetailsId");

                    b.HasIndex("UserDetailsId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MAMS.API.Models.DoctorAvailableDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<string>("Available_Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailableDetails");
                });

            modelBuilder.Entity("MAMS.API.Models.DoctorDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Auth_Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birth_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Blood_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Doctor_Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hospital_Affiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalCouncilRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modified_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonalId_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personal_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Specialization_Id")
                        .HasColumnType("int");

                    b.Property<int>("Specializations_Id")
                        .HasColumnType("int");

                    b.Property<int>("SuserId")
                        .HasColumnType("int");

                    b.Property<string>("UserTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Specializations_Id");

                    b.HasIndex("SuserId")
                        .IsUnique();

                    b.ToTable("DoctorDetails");
                });

            modelBuilder.Entity("MAMS.API.Models.MedicalRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Appointment_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("Doctor_PersonalId")
                        .HasColumnType("int");

                    b.Property<string>("Prescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment_plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("User_PersonalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorDetailsId");

                    b.HasIndex("UserDetailsId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("MAMS.API.Models.PatientDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Appointment_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalIdType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegisteredUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Appointment_Id")
                        .IsUnique();

                    b.ToTable("PatientDetails");
                });

            modelBuilder.Entity("MAMS.API.Models.Specializations", b =>
                {
                    b.Property<int>("Specializations_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Specializations_Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Record_Status")
                        .HasColumnType("int");

                    b.Property<string>("Specializations_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Specializations_Id");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("MAMS.API.Models.Suser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Susers");
                });

            modelBuilder.Entity("MAMS.API.Models.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Appointment_Id")
                        .HasColumnType("int");

                    b.Property<string>("Created_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Doctor_fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hospital_fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Modified_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PatientDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Appointment_Id")
                        .IsUnique();

                    b.HasIndex("PatientDetailsId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MAMS.API.Models.UserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birth_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Blood_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modified_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonalId_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personal_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuserId")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionsId")
                        .HasColumnType("int");

                    b.Property<string>("UserTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SuserId")
                        .IsUnique();

                    b.HasIndex("TransactionsId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("MAMS.API.Models.Views.Doctors", b =>
                {
                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<string>("Available_Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("SuserId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("View_Doctors", (string)null);
                });

            modelBuilder.Entity("MAMS.API.Models.Appointments", b =>
                {
                    b.HasOne("MAMS.API.Models.DoctorAvailableDetails", null)
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorAvailableDetailsId");

                    b.HasOne("MAMS.API.Models.DoctorDetails", null)
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorDetailsId");

                    b.HasOne("MAMS.API.Models.UserDetails", null)
                        .WithMany("Appointmentst")
                        .HasForeignKey("UserDetailsId");
                });

            modelBuilder.Entity("MAMS.API.Models.DoctorAvailableDetails", b =>
                {
                    b.HasOne("MAMS.API.Models.DoctorDetails", "DoctorDetails")
                        .WithMany("AvailableDetails")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorDetails");
                });

            modelBuilder.Entity("MAMS.API.Models.DoctorDetails", b =>
                {
                    b.HasOne("MAMS.API.Models.Specializations", "Specialization")
                        .WithMany()
                        .HasForeignKey("Specializations_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAMS.API.Models.Suser", "Suser")
                        .WithOne("DoctorDetails")
                        .HasForeignKey("MAMS.API.Models.DoctorDetails", "SuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("Suser");
                });

            modelBuilder.Entity("MAMS.API.Models.MedicalRecords", b =>
                {
                    b.HasOne("MAMS.API.Models.DoctorDetails", null)
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorDetailsId");

                    b.HasOne("MAMS.API.Models.UserDetails", null)
                        .WithMany("MedicalRecords")
                        .HasForeignKey("UserDetailsId");
                });

            modelBuilder.Entity("MAMS.API.Models.PatientDetails", b =>
                {
                    b.HasOne("MAMS.API.Models.Appointments", "Appointments")
                        .WithOne("PatientDetails")
                        .HasForeignKey("MAMS.API.Models.PatientDetails", "Appointment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MAMS.API.Models.Transactions", b =>
                {
                    b.HasOne("MAMS.API.Models.Appointments", "Appointments")
                        .WithOne("Transactions")
                        .HasForeignKey("MAMS.API.Models.Transactions", "Appointment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAMS.API.Models.PatientDetails", null)
                        .WithMany("Transactions")
                        .HasForeignKey("PatientDetailsId");

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MAMS.API.Models.UserDetails", b =>
                {
                    b.HasOne("MAMS.API.Models.Suser", "Suser")
                        .WithOne("UserDetails")
                        .HasForeignKey("MAMS.API.Models.UserDetails", "SuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAMS.API.Models.Transactions", "Transactions")
                        .WithMany()
                        .HasForeignKey("TransactionsId");

                    b.Navigation("Suser");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MAMS.API.Models.Appointments", b =>
                {
                    b.Navigation("PatientDetails")
                        .IsRequired();

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MAMS.API.Models.DoctorAvailableDetails", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MAMS.API.Models.DoctorDetails", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailableDetails");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("MAMS.API.Models.PatientDetails", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MAMS.API.Models.Suser", b =>
                {
                    b.Navigation("DoctorDetails")
                        .IsRequired();

                    b.Navigation("UserDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("MAMS.API.Models.UserDetails", b =>
                {
                    b.Navigation("Appointmentst");

                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
